In [22]:
!pip install -q -U tensorflow-text

     |████████████████████████████████| 4.4 MB 6.5 MB/s 


In [23]:
import tensorflow_hub as hub
import tensorflow_text as text

In [8]:
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [9]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [18]:
text_test = ['Hi Kdev here','How are you my friend']
text_preprocessed  = bert_preprocess_model(text_test)

In [19]:
text_preprocessed

{'input_mask': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>,
 'input_type_ids': <tf.Tensor: shape

In [20]:
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [21]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [22]:
bert_model = hub.KerasLayer(encoder_url)

bert_results = bert_model(text_preprocessed)

In [23]:
bert_results.keys()

dict_keys(['encoder_outputs', 'pooled_output', 'default', 'sequence_output'])

In [24]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.89830524, -0.35525605, -0.47196814, ..., -0.21401452,
        -0.6612691 ,  0.9208503 ],
       [-0.9218879 , -0.42685682, -0.65548474, ..., -0.4061718 ,
        -0.72357804,  0.93282527]], dtype=float32)>

In [25]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.21536902,  0.22750793, -0.01309027, ..., -0.13875116,
          0.31379458,  0.25117874],
        [ 0.28461486,  0.14015874,  0.91005063, ..., -0.07950252,
          0.681727  , -0.54576933],
        [-0.01899551, -0.45669204,  0.4272196 , ..., -0.00628532,
          0.2907481 , -0.42427772],
        ...,
        [-0.19448829,  0.0675825 ,  0.7119853 , ...,  0.2318607 ,
          0.11417285,  0.07324292],
        [-0.26176876, -0.21196856,  0.19851908, ...,  0.15129998,
          0.04212089, -0.22438136],
        [-0.04034657, -0.14208567,  0.39592135, ...,  0.08413899,
          0.06739867, -0.0887217 ]],

       [[ 0.12007437, -0.12229775, -0.19758838, ..., -0.1651526 ,
          0.22818777,  0.18754217],
        [-0.3532834 , -0.63208175, -0.42162517, ...,  0.7163511 ,
          0.99777377, -0.15440162],
        [ 0.6281159 , -1.2303284 , -0.08428119, ..., -0.19899304,
          0.35116702, -0.01332629],
        ...,

In [28]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.14369148,  0.03370704, -0.07099659, ..., -0.00377933,
           0.04449377,  0.05319013],
         [ 0.69332874, -0.681258  ,  0.9643074 , ..., -0.73207545,
          -0.4908904 , -1.3037468 ],
         [-0.62725866, -0.5414914 ,  0.11200383, ..., -0.88073033,
           0.00412771,  0.2683816 ],
         ...,
         [-0.01704623, -0.24020658,  0.64345527, ...,  0.44407275,
          -0.33564138, -0.03849863],
         [-0.10408924, -0.25206843,  0.5074964 , ...,  0.4594819 ,
          -0.2583943 , -0.13180897],
         [ 0.04253963, -0.18195105,  0.52787644, ...,  0.77682376,
          -0.5622132 , -0.21499518]],
 
        [[ 0.16533366,  0.03246141, -0.08937668, ...,  0.01101537,
           0.06946816,  0.11842743],
         [ 0.16235912,  1.3463134 , -1.1205297 , ...,  0.17765269,
           0.46922106,  0.7657939 ],
         [ 0.2861266 ,  0.25388002,  0.767813  , ..., -0.30190396,
           0.46514985,  0.06

In [29]:
len(bert_results['encoder_outputs'])

12

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/DatasetSpamClassifier/spam.csv',engine='python')

In [3]:
df.head(5)

v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [4]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [5]:
df.head(10)

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [6]:
df = df.rename(columns={"v1":"Category"})

In [7]:
df = df.rename(columns={"v2":"Message"})

In [8]:
df.head(10)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...

In [9]:
df.groupby('Category').describe()

Message                                                               
           count unique                                                top freq
Category                                                                       
ham         4825   4516                             Sorry, I'll call later   30
spam         747    653  Please call our customer service representativ...    4

In [10]:
df_spam = df[df['Category'] == 'spam']
df_spam.shape

(747, 2)

In [11]:
df_ham = df[df['Category']=='ham']
df_ham.shape

(4825, 2)

In [12]:
df_ham_downsampled = df_ham.sample(df_spam.shape[0])
df_ham_downsampled.shape

(747, 2)

In [13]:
df_balanced = pd.concat([df_spam,df_ham_downsampled])
df_balanced.shape


(1494, 2)

In [14]:
df_balanced['Category'].value_counts()

spam    747
ham     747
Name: Category, dtype: int64

In [15]:
df_balanced['spam'] = df_balanced['Category'].apply(lambda x : 1 if x=='spam' else 0)

In [16]:
df_balanced.sample(5)

Category                                            Message  spam
1759      ham  Do u ever get a song stuck in your head for no...     0
3060      ham  What u talking bout early morning? It's almost...     0
2118     spam  U can WIN �100 of Music Gift Vouchers every we...     1
1992     spam  Free tones Hope you enjoyed your new content. ...     1
4196     spam  FREE for 1st week! No1 Nokia tone 4 ur mob eve...     1

In [17]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(df_balanced['Message'],df_balanced['spam'],stratify = df_balanced['spam'])

In [18]:
X_train.head(4)

2472    Final Chance! Claim ur �150 worth of discount ...
2729    Urgent! Please call 09066612661 from your land...
1128    Ur HMV Quiz cash-balance is currently �500 - t...
5071    WIN a �200 Shopping spree every WEEK Starting ...
Name: Message, dtype: object

In [19]:
X_test.head(4)

2146                            So can collect ur laptop?
5269    If you don't, your prize will go to another cu...
1300    Those cocksuckers. If it makes you feel better...
3162    This is the 2nd time we have tried to contact ...
Name: Message, dtype: object

In [24]:
bert_preprocess = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3')
bert_encoder = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4')

In [25]:

def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.84351707, -0.5132728 , -0.88845724, ..., -0.74748844,
        -0.7531474 ,  0.91964495],
       [-0.87208337, -0.5054394 , -0.94446665, ..., -0.8584749 ,
        -0.71745324,  0.8808295 ]], dtype=float32)>

In [27]:
import tensorflow as tf


In [28]:
# BERT layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# NN layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [29]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
text (InputLayer)               [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_mask': (None 0           text[0][0]                       
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'pooled_output': (N 109482241   keras_layer[0][0]                
                                                                 keras_layer[0][1]                
                                                                 keras_layer[0][2]                
______________________________________________________________________________________________

In [30]:
len(X_train)

1120

In [31]:
METRICS = [
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=METRICS)

In [32]:
model.fit(X_train,y_train,epochs=15)

Epoch 1/15
35/35 [==============================] - 18s 297ms/step - loss: 0.6205 - accuracy: 0.6830 - precision: 0.6983 - recall: 0.6446
Epoch 2/15
35/35 [==============================] - 10s 297ms/step - loss: 0.5071 - accuracy: 0.8125 - precision: 0.7907 - recall: 0.8500
Epoch 3/15
35/35 [==============================] - 10s 299ms/step - loss: 0.4418 - accuracy: 0.8509 - precision: 0.8453 - recall: 0.8589
Epoch 4/15
35/35 [==============================] - 11s 302ms/step - loss: 0.4020 - accuracy: 0.8741 - precision: 0.8695 - recall: 0.8804
Epoch 5/15
35/35 [==============================] - 11s 303ms/step - loss: 0.3689 - accuracy: 0.8795 - precision: 0.8571 - recall: 0.9107
Epoch 6/15
35/35 [==============================] - 11s 303ms/step - loss: 0.3495 - accuracy: 0.8804 - precision: 0.8685 - recall: 0.8964
Epoch 7/15
35/35 [==============================] - 11s 305ms/step - loss: 0.3308 - accuracy: 0.8964 - precision: 0.8841 - recall: 0.9125
Epoch 8/15
35/35 [================

In [33]:
model.evaluate(X_test,y_test)

12/12 [==============================] - 5s 295ms/step - loss: 0.2114 - accuracy: 0.9519 - precision: 0.9378 - recall: 0.9679


[0.2114037722349167,
 0.9518716335296631,
 0.9378238320350647,
 0.9679144620895386]

In [34]:
y_predicted = model.predict(X_test)
y_predicted = y_predicted.flatten()

In [35]:

import numpy as np

y_predicted = np.where(y_predicted > 0.5, 1, 0)
y_predicted

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,

In [36]:

from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, y_predicted)
cm

array([[175,  12],
       [  6, 181]])

In [37]:
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.97      0.94      0.95       187
           1       0.94      0.97      0.95       187

    accuracy                           0.95       374
   macro avg       0.95      0.95      0.95       374
weighted avg       0.95      0.95      0.95       374



In [38]:
reviews = [
    'Enter a chance to win $5000, hurry up, offer valid until march 31, 2021',
    'You are awarded a SiPix Digital Camera! call 09061221061 from landline. Delivery within 28days. T Cs Box177. M221BP. 2yr warranty. 150ppm. 16 . p p£3.99',
    'it to 80488. Your 500 free text messages are valid until 31 December 2005.',
    'Hey Sam, Are you coming for a cricket game tomorrow',
    "Why don't you wait 'til at least wednesday to see if you get your ."
]
model.predict(reviews)

array([[0.7658039 ],
       [0.88212126],
       [0.78753203],
       [0.14537375],
       [0.06312909]], dtype=float32)

In [40]:
model.save("bertSpam")

INFO:tensorflow:Assets written to: bertSpam/assets


INFO:tensorflow:Assets written to: bertSpam/assets


In [41]:
model.save('/content/drive/MyDrive/DatasetSpamClassifier')

INFO:tensorflow:Assets written to: /content/drive/MyDrive/DatasetSpamClassifier/assets


INFO:tensorflow:Assets written to: /content/drive/MyDrive/DatasetSpamClassifier/assets
